# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  default:
    vars:
      _FULL_HASH:
        sh: "git rev-parse HEAD"
      _PARTIAL_HASH:
        sh: "git rev-parse --short=8 HEAD"
    deps:
      - dev
    cmds:
      - "sed -i '' 's/_FULL_HASH/{{._FULL_HASH}}/' _output/index.html"
      - "sed -i '' 's/_PARTIAL_HASH/{{._PARTIAL_HASH}}/' _output/index.html"
  dev:
    desc: watch
    watch: true
    sources:
      - src/**
    cmds:
      - "rm -rf _output/"
      - "cp -r src/ _output/"
      - "npm run gen"
