# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    name: "Build & Release"
    environment:
      name: Cloudflare Pages
      url: "${{ steps.deploy.outputs.deployment-url }}"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: "actions/setup-node@v4"
        with:
          node-version: 22
          cache: "pnpm"
      - name: Get pnpm store directory
        shell: bash
        run: |-
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: "${{ env.STORE_PATH }}"
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: "${{ runner.os }}-pnpm-store-"
      - run: pnpm install
      - run: "npm run build"
      - uses: "cloudflare/wrangler-action@v3"
        id: deploy
        with:
          apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          command: "pages deploy .output/public/ --project-name=www-io --branch=${{ github.ref_name }} --commit-hash=${{ github.head }}"
