# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Preview
on:
  pull_request:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    name: "Build & Release"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: "actions/setup-node@v4"
        with:
          node-version: 22
          cache: "pnpm"
      - name: Get pnpm store directory
        shell: bash
        run: |-
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: "${{ env.STORE_PATH }}"
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: "${{ runner.os }}-pnpm-store-"
      - run: pnpm install
      - run: "npm run build"
      - uses: "cloudflare/wrangler-action@v3"
        id: deploy
        with:
          apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          command: "pages deploy .output/public/ --project-name=www-io --branch=${{ github.ref_name }} --commit-hash=${{ github.head }}"
      - uses: "actions/github-script@v7"
        if: "github.event_name == 'pull_request'"
        env:
          DEPLOYMENT_URL: "${{ steps.deploy.outputs.deployment-url }}"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |-
            const { DEPLOYMENT_URL } = process.env;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Deployed to Cloudflare Pages: ${DEPLOYMENT_URL}`
            });
